### ISSUE TITLE
Lock room setup not looking at %localappdata%\openvr\openvrpaths.vrpath

### ISSUE THREAD

**Issue by gac123** [alsoknownasfoo/ViveArcadeTool#2]
it is assuming the roomconfig resides in the default

this causes issues here:
![image](https://user-images.githubusercontent.com/7746819/57984192-a0cd5500-7a59-11e9-938a-b4716c37f559.png)

you can chose another chaperone that resides in another folder but when asked:
![image](https://user-images.githubusercontent.com/7746819/57984200-bcd0f680-7a59-11e9-934b-d18e68c20364.png)

it will take the lighthousedb json from the default folder and not \lighthouse\ where the user specified a different chaperone, so you end up with an unusable mix

**Comment by alsoknownasfoo** [comment]
Funny that you raised this issue. I was working with Infinadeck last week and realized that the standalone SteamVR installer was in a different path and thought to myself, I'll just grab the paths from vrpaths. Thanks for raising this issue.

**Comment by alsoknownasfoo** [comment]
Also, to clarify, I chose to not deal with potential issues with windows file locking mechanisms as well as simplifying the logic by creating a copy of the file you choose and using that file for overwriting SteamVR's operational files.  The file that you choose is actually copied to %APPDATA%\ViveArcadeTool\ChaperoneLock\.

If for some reason you need to dynamically modify the chaperone, overwrite those files in that directory.

**Comment by gac123** [comment]
great!

but how does the tool choose a universe if multiple are defined in the lighthousedb and chaperone file?

or would you suggest to have lighthousedb and chaperone files per universe and just push those 2 files whenever a different room is used?

our usecase is the following;

we have a pool of HP Z VR backpacks with vive pro's and multiple rooms with each 4 basestations and thus predefined universes
let's say room 2 is free and we have a group of 6, then we just take 6 backpacks, get it on the players and the universe switches to the correct one because it sees the corresponding basestations

but our rooms aren't exactly rooms, see it as a giant warehouse and the rooms are only seperated by a curtain
we are currently having tracking issues, possibly because of stray signals from other basestations (on different channels), so we are looking for ways to lock down the lighthousedb and chaperone files that would reliably give us predictable results

**Comment by alsoknownasfoo** [comment]
From what I understand, SteamVR chooses the universe based on the bases it sees. The lighthouseDB contains the database of the bases and which universe it belongs to. It will then choose the associated room setup definition from the chaperone file based on the universe ID. Both files can have multiple definitions to support different rooms.

The tool has a simply lighthouseDB editor that helps you modify the bases associated with the respective universe ID you choose. To modify multiple universes, you would need to run it twice by deselecting then reselecting the option and choosing the different universe ID to modify. I'll look into providing a more robust editor in the future.

Because of your unique setup, I would recommend modifying your lighthouseDB to have the two universe definitions with the 4 bases for each room in their own respective universe definition. In your chaperone, you would be sure to have two room setup definitions for each room referencing the respective universe id's. Then have the tool lock all backpacks to those two files. 

Or an easier option would be to just purge both files and starting out fresh and just make sure that while you're setting up each space to just turn off the other room's bases.

**Comment by alsoknownasfoo** [comment]
Fixed in https://github.com/alsoknownasfoo/ViveArcadeTool/tree/0.8.6

**Comment by gac123** [comment]
> Or an easier option would be to just purge both files and starting out fresh and just make sure that while you're setting up each space to just turn off the other room's bases.

that's exactly what I do, this is the only clean way to do it

but my question is how does the "lock room setup to a universe" work? your tool modifies all entries from the main lighthousedb and saves it to it's own location
but how does steamvr then know to only use that universe?

**Comment by gac123** [comment]
because.. I first do the room setups room per room with all other room basestations offline (they are also all on their unique channels, each basestation), and I save each lighthousedb and chaperone in a seperate folder (room1, room2, etc..) i clean them of any "known objects" then I merge all those files;
see my attachment
[venue3_room0.zip](https://github.com/alsoknownasfoo/ViveArcadeTool/files/3215907/venue3_room0.zip)(contains 4 rooms)

but lets say I want to make sure that a computer is locked to a certain universe and ignore everything else, I could use those individual lighthousedb and chaperone files (each just containing the details of that 1 room, none other, for example: [venue3_room1.zip](https://github.com/alsoknownasfoo/ViveArcadeTool/files/3215936/venue3_room1.zip)) and copy them to your locked room folder when a backpack is used in a different room with those respective lighthousedb and chaperone files

does your tool need to be closed first? do I need to restart steamvr? do I need to restart the headset? or best take everything offline/shutdown and reboot?
